### ISSUE TITLE
실행하면 오류가 발생합니다.

### ISSUE THREAD

**Issue by soypabloo** [byongshintv/backjoon-cpp-resolver#2]
wsl(우분투)환경에서 사용하려고 설치했으니 이러한 오류가 발생합니다.
npm start                                                                                                              ✔  04:36:33  

> backjoon-cpp-resolver@2.22 start
> node src/index

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './Printer'
Require stack:
- /home/soypablo/coding_test/backjoon-cpp-resolver/src/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/soypablo/coding_test/backjoon-cpp-resolver/src/index.js:5:17)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/soypablo/coding_test/backjoon-cpp-resolver/src/index.js' ]
}

**Comment by byongshintv** [comment]
오류의 원인으로 보이는 문제점을 수정했습니다. 

리눅스 환경에서 테스트 할 수단이 없어 그런데 다시 오류가 발생하면 알려주시면 감사드리겠습니다

**Comment by soypabloo** [comment]
업데이트 후에도 동일한 결과가 나옵니다..
npm start                                                                                            ✔  21:20:17  

> backjoon-cpp-resolver@2.22 start
> node src/index

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './Printer'
Require stack:
- /home/soypablo/coding_test/backjoon-cpp-resolver/src/compile.js
- /home/soypablo/coding_test/backjoon-cpp-resolver/src/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/soypablo/coding_test/backjoon-cpp-resolver/src/compile.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/soypablo/coding_test/backjoon-cpp-resolver/src/compile.js',
    '/home/soypablo/coding_test/backjoon-cpp-resolver/src/index.js'
  ]
}

Node.js v17.1.0

**Comment by byongshintv** [comment]
우분투 lts환경에서 노드 17.1.0버전으로 돌려봤는데 이상하게 저는 잘되네요 

이번주 안으로 수정해보고 다시 말씀드리겠습니다
